version: '3.8'

services:
  dwh-scheduler:
    build:
      context: ../..
      dockerfile: DWH/init_scripts/Dockerfile
    container_name: dwh-scheduler
    env_file:
      - ../.env
    environment:
      - TZ=America/Costa_Rica
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - dwh_default

networks:
  dwh_default:
    external: true
    name: dwh_default
