version: '3.8'

services:
  sqlserver:
    build:
      context: ..
      dockerfile: MSSQL/Dockerfile
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BasesDatos2!
    ports:
      - "1435:1433"
    volumes:
      - sqldata:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  sqldata:
