services:
  mysql:
    image: mysql:8.0
    container_name: mysql-transactional
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sales_mysql}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user123}
      TZ: America/Costa_Rica
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mysql-network
      - dwh-network

networks:
  mysql-network:
    driver: bridge
  dwh-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
