version: '3.8'

services:
  sqlserver-dw:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: sqlserver-dw
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BasesDatos2!
    ports:
      - "1434:1433"
    volumes:
      - sqldatadw:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqldatadw: