version: '3.8'

services:
  sqlserver-dw:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dw
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BasesDatos2!
    ports:
      - "1434:1433"
    volumes:
      - sqldatadw:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqldatadw: